In [55]:
import pandas as pd

df = pd.read_csv('./car_complain.csv')
df

,id,brand,car_model,type,desc,problem,datetime,status
0,568936,一汽-大众,速腾,2020款 280TSI DSG 舒适型 国VI,一汽大众速腾发动机运转时汽油箱存在异响,"H147,",2021-01-30,信息审核
1,568935,东风日产,逍客,2021款 2.0L CVT 豪华版,东风日产逍客行驶中车身共振发动机噪音大\t,"A38,H268,",2021-01-30,信息审核
2,568934,上汽大众,途观L,2019款 280TSI 自动 两驱 全景舒适版 国V,上汽大众途观L行驶过程中变速箱异响顿挫,"B33,B19,",2021-01-30,信息审核
3,568932,北京奔驰,奔驰GLC,2020款 改款 GLC 260 L 4MATIC 动感型,北京奔驰GLC刹车异响影响到正常用车\t,"E43,",2021-01-30,信息审核
4,568913,一汽丰田,卡罗拉,2021款 1.2T S-CVT 先锋版,一汽丰田卡罗拉变速箱顿挫异响越来越严重,"B33,B19,",2021-01-30,信息审核
...,...,...,...,...,...,...,...,...
595,567571,一汽-大众,速腾,2020款 200TSI DSG 舒适型 国VI,一汽大众速腾发动机故障灯常亮而且有异响,"A9,A34,",2021-01-26,处理反馈
596,567569,上汽通用五菱,宝骏E100,2019款 250KM 智行版,宝骏E100动力电池故障导致续航里程短,"H343,",2021-01-26,用户评分
597,567568,领克,领克01,2021款 2.0TD 两驱 型Pro,领克01自动雨刮速度过快玻璃出现划痕,"H60,",2021-01-26,用户评分
598,567567,观致汽车,观致3,2018款 1.6T 自动 旗舰型 三厢,观致3发动机熄火启动困难维修无配件更换,"A14,A44,N318,",2021-01-26,信息审核
599,567566,北京奔驰,奔驰GLB,2020款 改款 GLB 200 动感型,奔驰GLB冷启动发动机熄火故障灯亮天窗异响,"A34,A14,H89,",2021-01-26,处理反馈

In [56]:
# # 0代表没有,1代表有
df=df.drop('problem',axis = 1).join(df.problem.str.get_dummies(','))
df

,id,brand,car_model,type,desc,datetime,status,A114,A12,A13,...,N320,O305,O324,O326,O348,O353,P327,Q322,Q349,Q350
0,568936,一汽-大众,速腾,2020款 280TSI DSG 舒适型 国VI,一汽大众速腾发动机运转时汽油箱存在异响,2021-01-30,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,568935,东风日产,逍客,2021款 2.0L CVT 豪华版,东风日产逍客行驶中车身共振发动机噪音大\t,2021-01-30,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,568934,上汽大众,途观L,2019款 280TSI 自动 两驱 全景舒适版 国V,上汽大众途观L行驶过程中变速箱异响顿挫,2021-01-30,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,568932,北京奔驰,奔驰GLC,2020款 改款 GLC 260 L 4MATIC 动感型,北京奔驰GLC刹车异响影响到正常用车\t,2021-01-30,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,568913,一汽丰田,卡罗拉,2021款 1.2T S-CVT 先锋版,一汽丰田卡罗拉变速箱顿挫异响越来越严重,2021-01-30,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,567571,一汽-大众,速腾,2020款 200TSI DSG 舒适型 国VI,一汽大众速腾发动机故障灯常亮而且有异响,2021-01-26,处理反馈,0,0,0,...,0,0,0,0,0,0,0,0,0,0
596,567569,上汽通用五菱,宝骏E100,2019款 250KM 智行版,宝骏E100动力电池故障导致续航里程短,2021-01-26,用户评分,0,0,0,...,0,0,0,0,0,0,0,0,0,0
597,567568,领克,领克01,2021款 2.0TD 两驱 型Pro,领克01自动雨刮速度过快玻璃出现划痕,2021-01-26,用户评分,0,0,0,...,0,0,0,0,0,0,0,0,0,0
598,567567,观致汽车,观致3,2018款 1.6T 自动 旗舰型 三厢,观致3发动机熄火启动困难维修无配件更换,2021-01-26,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599,567566,北京奔驰,奔驰GLB,2020款 改款 GLB 200 动感型,奔驰GLB冷启动发动机熄火故障灯亮天窗异响,2021-01-26,处理反馈,0,0,0,...,0,0,0,0,0,0,0,0,0,0

按照brand统计 投诉总数,不同problem类型的总数 <br>
按照投诉总数进行排序
按照指定的problem类型进行排序

In [62]:
# 数据清洗,将别名合并
# def f(x):
#     x = x.replace('一汽-大众','一汽大众')
#     return
# df['brand'] = df['band'].apply(f)
result2 = df.groupby(['brand'])['id'].agg(['count'])
result2

           count
brand
BEIJING汽车      3
DS汽车           1
Jeep（进口）       1
SWM斯威汽车        4
一汽-大众         74
...          ...
长安福特          18
长安马自达          2
陕汽德龙           1
雷克萨斯           1
领克             6

[80 rows x 1 columns]

In [59]:
tags = df.columns[8:]
tags

Index(['A12', 'A13', 'A136', 'A14', 'A163', 'A18', 'A189', 'A191', 'A24',
       'A255',
       ...
       'N320', 'O305', 'O324', 'O326', 'O348', 'O353', 'P327', 'Q322', 'Q349',
       'Q350'],
      dtype='object', length=165)

In [60]:
result = df.groupby(['brand'])[tags].agg(['sum'])
result

,A12,A13,A136,A14,A163,A18,A189,A191,A24,A255,...,N320,O305,O324,O326,O348,O353,P327,Q322,Q349,Q350
,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,...,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum
brand,,,,,,,,,,,,,,,,,,,,,
BEIJING汽车,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DS汽车,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Jeep（进口）,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SWM斯威汽车,1,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
一汽-大众,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
长安福特,2,0,0,0,1,0,0,2,2,0,...,0,0,0,0,0,0,0,0,0,1
长安马自达,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
陕汽德龙,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
雷克萨斯,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
领克,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [63]:
result2 = result.merge(result2,left_index=True,right_index=True,how='left')
result2

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py:643: UserWarning: merging between different levels can give an unintended result (2 levels on the left,1 on the right)
  warnings.warn(msg, UserWarning)

,"(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A163, sum)","(A18, sum)","(A189, sum)","(A191, sum)","(A24, sum)","(A255, sum)",...,"(O305, sum)","(O324, sum)","(O326, sum)","(O348, sum)","(O353, sum)","(P327, sum)","(Q322, sum)","(Q349, sum)","(Q350, sum)",count
brand,,,,,,,,,,,,,,,,,,,,,
BEIJING汽车,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
DS汽车,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Jeep（进口）,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
SWM斯威汽车,1,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,4
一汽-大众,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
长安福特,2,0,0,0,1,0,0,2,2,0,...,0,0,0,0,0,0,0,0,1,18
长安马自达,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
陕汽德龙,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
雷克萨斯,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
领克,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,6

In [64]:
result2.reset_index(inplace=True)
result2

,brand,"(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A163, sum)","(A18, sum)","(A189, sum)","(A191, sum)","(A24, sum)",...,"(O305, sum)","(O324, sum)","(O326, sum)","(O348, sum)","(O353, sum)","(P327, sum)","(Q322, sum)","(Q349, sum)","(Q350, sum)",count
0,BEIJING汽车,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
1,DS汽车,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,Jeep（进口）,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,SWM斯威汽车,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,4
4,一汽-大众,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,长安福特,2,0,0,0,1,0,0,2,2,...,0,0,0,0,0,0,0,0,1,18
76,长安马自达,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
77,陕汽德龙,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
78,雷克萨斯,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
79,领克,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,6

In [66]:
result2.to_csv('./result.csv')

In [69]:
# 按照count,从大到小进行排序
result2 = result2.sort_values('count',ascending=False)
result2

,brand,"(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A163, sum)","(A18, sum)","(A189, sum)","(A191, sum)","(A24, sum)",...,"(O305, sum)","(O324, sum)","(O326, sum)","(O348, sum)","(O353, sum)","(P327, sum)","(Q322, sum)","(Q349, sum)","(Q350, sum)",count
4,一汽-大众,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,74
20,东风日产,0,1,0,1,1,0,0,0,2,...,0,0,0,0,0,0,0,0,0,45
11,上汽大众,1,0,0,1,1,0,0,0,3,...,0,1,0,0,1,0,0,0,0,41
36,吉利汽车,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,34
47,广汽本田,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,星途,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
53,昌河铃木,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
52,新大洲本田,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,东风英菲尼迪,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
64,理想,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [70]:
query = ('A12','sum')
result2.sort_values(query,ascending=False)

,brand,"(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A163, sum)","(A18, sum)","(A189, sum)","(A191, sum)","(A24, sum)",...,"(O305, sum)","(O324, sum)","(O326, sum)","(O348, sum)","(O353, sum)","(P327, sum)","(Q322, sum)","(Q349, sum)","(Q350, sum)",count
47,广汽本田,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,32
75,长安福特,2,0,0,0,1,0,0,2,2,...,0,0,0,0,0,0,0,0,1,18
21,东风本田,2,2,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,16
4,一汽-大众,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,74
9,一汽奔腾,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,东风日产,0,1,0,1,1,0,0,0,2,...,0,0,0,0,0,0,0,0,0,45
48,广汽菲克Jeep,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
76,长安马自达,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
8,一汽吉林,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
64,理想,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1